
= Profiles and messages

All messages contains ProfileID and CustomizationID. ProfileID identifies what business process a given message is part of, and CustomizationID identifies the kind of message and the rules applied.

Profiles are connected to one business process, and may contain multiple document types. Valid document instances shall contain corresponding ProfileID and CustomizationID.


IMPORTANT: CustomizationID is a string without spaces. The list below contains spaces in CustomizationID to make them easier to read. *Make sure to remove any spaces before use.*


== Customization and Profile identifiers

In the table below you will find the values to be used as the specification identifier and the business process type for this profile

[cols="4s,4a,4a", options="header"]
|===
| Type
| Element `cbc:CustomizationID`
| Element `cbc:ProfileID`


| EHF CV Request
| urn:fdc:difi.no:2017:ehf:pacr:1.0
.2+| urn:fdc:difi.no:2017:ehf:profile:03:1.0

| EHF CV
|urn:fdc:difi.no:2017:ehf:pac:1.0

|===
