= Clearance

Jobs within certain departments of the government or private sectors require that employees
have a specific level of clearance. For example are security clearances required by the government
employers who have access to sensitive information.

== Information specific to CV request

A Contracting Authority can state clearance requirement (main requirement) and an alternative
requirement in the CV request. The alternative requirement is optional, but may be used when an alternative
clearance can be accepted.

All clearances need to be identified uniquely to ensure that the clearance can be referenced to in the
CV. The element `cv-req:Requirement` shall be used to state if the clerarance *should* or *must* be present. The Economic Operators
will only provide qualified candidates, and this makes it easier to do the rating.

Contracting Authorities must specify the level of clearance (`cv-req:Level`) by using codelist
clearance level. Note that the clearance level is a minimum requirement, which means candidate with
higher level of clearance is qualified.

We often need a candidate that has active clearance through the whole job period. The Contracting
Authority must specify an expiration date (`cv-req:ExpirationDate`), which defines the time period
the clearance needs to be active.

.Example of the requested clearance in the CV request
[source, xml, indent=0]
----
include::../{snippet-dir-cv-request}/cv-request.xml[tags=Clearance]
----
<1> Clearance identifier
<2> Clearance requirement - indicate whether a candidate needs to fulfill the clearance requirement.  According to codelist Requirement code (chapter 5.5).
<3> Clearance type, see examples below
<4> Clearance level according to codelist Clearance level (chapter 5.1)
<5> Expiration date

.Example of the requested clearance in the CV request with alternative requirement
[source, xml, indent=0]
----
include::../{snippet-dir-cv-request}/cv-request.xml[tags=ClearanceAlternative]
----
<1> Clearance identifier
<2> Clearance requirement - indicate whether a candidate needs to fulfill the clearance requirement.  According to codelist Requirement code (chapter 5.5).
<3> Clearance type, see examples below
<4> Clearance level according to codelist Clearance level (chapter 5.1)
<5> Expiration date
<6> Alternative clearance requirement


== Information specific to CV

Based on the clearance requirement, the Economic Operator needs to document the candidate's
clearance. 
The documentation of clearance can be stated as URI (`cv:URI`) or embedded document (`cv:EmbeddedDocumentBinaryObject`).

Candidates who don't fulfill the clearance requirement can describe the reason and whether this can
be done before the job period. Use element `cv:Description`. 

.Example of a description of clearance in CV as a response to requested clearance in CV request
[source, xml, indent=0]
----
include::../{snippet-dir-cv}/cv.xml[tags=Clearance]
----
<1> Clearance identifier
<2> Clearance type, see examples below
<3> Clearance level according to codelist Clearance level (chapter 5.1)
<4> Clearance expiration date
<5> Embedded document as binary object with `mimeCode`. Use Base64.
<6> Additional description related to clearance, e.g. if the clearance can be done before the job period if not in place already.

== Examples of clearance types

[source, xml, indent=0]
----
include::../../../_common/examples/clearance-type.xml[tags=ClearanceType]
----
