= Course and Certification

The course information group is used to state relevant courses that the candidate has taken. This information is not mandatory,
but might be relevant for some assignments.

There is a difference between certification and course. Certification has an exam/test that needs to be
passed, but not so for course.

== Information specific to CV request

A Contracting Authority can state both a course/certification requirement (main requirement) and an alternative
requirement in the CV request. The alternative requirement is optional, but in some cases other
similar courses can be accepted. As an example the Contracting Authority can accept other versions of the specific course/certification.
Note that the alternative requirements include the same information elements as the original requirement.

All courses and certifications need to be identified uniquely to ensure that the course can be referenced in the
CV. The element `cv-req:Requirement` shall be used to differentiate between courses that *should* and *must* be present. The Economic Operators
will only provide qualified candidates, and this makes it easier to do the rating.

A course/certification must include either the element `cv-req:Type` or `cv-req:Title` to identify the specific course or
certification. Use type if the specific course is defined in the course codelist, otherwise use the title. Similarly for certification.

In course requirement, the Contacting Authority can specify which period (`cv-req:Period`) the candidate must finish the course. This can
be a date in the future. In a certification requirement the Contracting Authority can request that the
certification must be valid to a specific date (`cv-req:ValidTo`).

.Example of the requested course in the CV request
[source, xml, indent=0]
----
include::../{snippet-dir-cv-request}/cv-request.xml[tags=Course]
----
<1> Course identifier
<2> Course requirement - indicate whether a candidate needs to fulfill the course requirement.  According to codelist Requirement code (chapter 5.11).
<3> Course type  according to codelist Course type (chapter 5.4)
<4> Period

.Example of the requested course in the CV request with alternative requirement
[source, xml, indent=0]
----
include::../{snippet-dir-cv-request}/cv-request.xml[tags=CourseAlternative]
----
<1> Course identifier
<2> Course requirement - indicate whether a candidate needs to fulfill the course requirement.  According to codelist Requirement code (chapter 5.11).
<3> Course title
<4> Course version
<5> Period
<6> Alternative course requirement

.Example of the requested certification in the CV request
[source, xml, indent=0]
----
include::../{snippet-dir-cv-request}/cv-request.xml[tags=Certification]
----
<1> Certification identifier
<2> Certification requirement - indicate whether a candidate needs to fulfill the certification requirement.  According to codelist Requirement code (chapter 5.11).
<3> Certification type  according to codelist Certification type (chapter 5.1)
<4> A date certification is valid to

.Example of the requested certification in the CV request with alternative requirement
[source, xml, indent=0]
----
include::../{snippet-dir-cv-request}/cv-request.xml[tags=CertificationAlternative]
----
<1> Certification identifier
<2> Certification requirement - indicate whether a candidate needs to fulfill the certification requirement.  According to codelist Requirement code (chapter 5.11).
<3> Certification title
<4> Certification version
<5> A date certification must be valid to
<6> Alternative certification requirement

== Information specific to CV

Based on the course/certification requirement, the Economic Operator needs to document the candidate's course/certification.
For CV used in the job application process, fill in the relevant parts of course/certification information.

The element `cv:CourseReference` and `cv:CertificationReference` must correspond to the course requirement in the CV request.

It is possible to state information about the supplier of the course/certification. This might be relevant for some Contracting
Authorities, since different suppliers may offer the same course/certification with different content.


.Example of a description of course in CV as a response to requested course in CV request
[source, xml, indent=0]
----
include::../{snippet-dir-cv}/cv.xml[tags=Course-req]
----
<1> Course identifier
<2> Course title
<3> Course version
<4> Course period
<5> Information about the supplier of the course
<6> The supplier's organisation number. schemeID according to codelist Electronic address identifier (EAID) (chapter 5.18)
<7> The legal name of supplier
<8> Contact information of supplier expressed as email address
<9> The country where the supplier is registered - expressed as country code from the codelist
<10> Embedded document as binary object with `mimeCode`. Use Base64.
<11> URI to course document
<12> Course reference

.Example of a description of certification in CV as a response to requested course in CV request
[source, xml, indent=0]
----
include::../{snippet-dir-cv}/cv.xml[tags=Certification-req]
----
<1> Certification identifier
<2> Certification title
<3> Certification version
<4> A date certification is valid to
<5> Information about the supplier of the certification
<6> The supplier's organisation number. schemeID according to codelist Electronic address identifier (EAID) (chapter 5.18)
<7> The legal name of supplier
<8> Contact information of supplier expressed as email address
<9> The country where the supplier is registered - expressed as country code from the codelist
<10> Embedded document as binary object with `mimeCode`. Use Base64.
<11> URI to certification document
<12> Certification reference
