= Language skills

Language skills may be specified in CV request and CV. For certain assignments the language skill may be of 
great importance.

== Information specific to CV request

A Contracting Authority can state both a specific language requirement and an alternative requirement.
The alternative requirement is optional, but should be used if an alternative language is accepted.
As an example some Norwegian entities use Norwegian as primarily work language but may accept Swedish and Danish.
There is also possible to require several languages, for example Norwegian and English.
Note that the alternative requirements include the same information elements as the original requirement.

All language skills need to be identified uniquely, to ensure that the language skill can be referenced in the CV.
The element `cv-req:Requirement` shall be used to differentiate between languages skills that *should* and *must* be present.

Oral skill and written skill must be provided for each language skill requirement. The skill levels are based on
EU global standard. Note that the skill level is a minimum requirement. For example, the Contracting Authority wants a candidate
with a `B1` oral skill level. The candidate has an oral skill level on `A1`, which implies that the candidate is qualified.

.Example of the requested language skill in the CV request
[source, xml, indent=0]
----
include::../{snippet-dir-cv-request}/cv-request.xml[tags=LanguageSkills]
----
<1> Language skill identifier
<2> Language skill requirement - indicate whether a candidate needs to fulfill the language requirement.  According to codelist Requirement code (chapter 5.11).
<3> A specific language according to codelist ISO639 Language code (chapter 5.21)
<4> Oral skill
<5> Written skill

.Example of the requested language skill in the CV request with alternative requirements
[source, xml, indent=0]
----
include::../{snippet-dir-cv-request}/cv-request.xml[tags=LanguageSkillsAlternative]
----
<1> Language skill identifier
<2> Language skill requirement - indicate whether a candidate needs to fulfill the language requirement.  According to codelist Requirement code (chapter 5.11).
<3> A specific language according to codelist ISO639 Language code (chapter 5.21)
<4> Oral skill according to codelist Language level (chapter 5.6)
<5> Written skill according to codelist Language level (chapter 5.6)
<6> Alternative language skill requirements


== Information specific to CV

Based on the language skill requirements, the Economic Operator needs to document the candidate's language skills.
Oral skill and written skill must be provided for each language. The skill levels must be defined according to the
EU global standard codelist.

The element `cv:LanguageSkillsReference` must contain reference to the corresponding language skill requirement in the CV request.

.Example of a description of language skill in CV as a response to requested language skill in CV request
[source, xml, indent=0]
----
include::../{snippet-dir-cv}/cv.xml[tags=LanguageSkills-req]
----
<1> Language skill identifier
<2> A specific language according to codelist ISO639 Language code (chapter 5.21)
<3> Oral skill according to codelist Language level (chapter 5.6)
<4> Written skill according to codelist Language level (chapter 5.6)
<5> Contact information related to candidate's language skill
<6> Language skill reference
