= Personal Skills

Person skills contains information about a candidates abilities and strength.

== Information specific to CV request

A Contracting Authority can state personal skill requirement (main requirement) in the CV request.

All personal skills need to be identified uniquely to ensure that the personal skill can be
referenced in the CV.

Personal skills must include the element `cv-req:Type` to specify the type of personal skill requested.

.Example of the requested clearance in the CV request
[source, xml, indent=0]
----
include::../{snippet-dir-cv-request}/cv-request.xml[tags=PersonalSkills]
----
<1> Personal skill identifier
<2> Personal skill type, see examples below


== Information specific to CV

Based on the personal skill requirement, the economic operator must provide information
about the candidate's personal skills. 

It is possible to provide contact information to a person who can confirm the candidate's personal
skills.

.Example of a description of personal skills in CV as a response to requested personal skills in CV request
[source, xml, indent=0]
----
include::../{snippet-dir-cv}/cv.xml[tags=PersonalSkills]
----
<1> Personal skill identifier
<2> Type of personal skill, see examples below
<3> Contact information

== Examples of Personal skills

The list below gives examples of Peronal skills that can be requested.

[source, xml, indent=0]
----
include::../../../_common/examples/personal-skills.xml[tags=PersonalSkills]
----
