= Project Experience

Project experience is about a specific project that candidate has worked with.
This is not similar to work experience.

== Information specific to CV request

A contracting authority can specify a request for a project experience in several ways. There are many options.
For each project experience, there must be an experience type. In some cases, there is relevant to request a project experience
related to an industry, workplace (country), or sector.

The total year of experience can be specified in element `cv-req:RequiredTotalExperience`, where one can have a
lower bound (`cv-req:MinimumExperience`) and a upper bound (`cv-req:MaximumExperience`). The candidate must fulfill
the lower bound requirement. Another option is to only have lower bound or upper bound requirements.

In the CV request, the contracting authority can state the requested period for an project experience, using element
`cv-req:Period`. Implies that the candidate can only refer to project experience from this period. For example, if
a contracting authority only want candidates with project experience from last five years.

The description of experience need to be provided in element `cv-req:ExperienceDescription`, where candidate's role must
be specified in element `cv-req:Role`. It is also possible to describe the project activities and candidate's project
position percent (e.g. must have worked 100% with the project).

The project value can bed stated in element `cv-req:ExperienceValue`, where contracting authority can specify candidate's
project participation (need to be months), the size of project and the total value of the project.

.Example of the requested project experience in the CV request with alternative requirement
[source, xml, indent=0]
----
include::../{snippet-dir-cv-request}/cv-request.xml[tags=ProjectExperienceAlternative]
----
<1> Project experience identifier
<2> Project experience requirement - indicate whether a candidate needs to fulfill the project requirement
<3> Type of project experience
<4> Type of industry
<5> Workplace
<6> Job sector
<7> Total year of experience
<8> Period
<9> Candidate's position percent
<10> Role in project
<11> Description of project activities
<12> Project participation
<13> Total Project size
<14> Project value
<15> Alternative project experience

.Example of the requested project experience in the CV request
[source, xml, indent=0]
----
include::../{snippet-dir-cv-request}/cv-request.xml[tags=ProjectExperience]
----
<1> Project experience identifier
<2> Project experience requirement - indicate whether a candidate needs to fulfill the project requirement
<3> Type of project experience
<4> Type of industry
<5> Workplace
<6> Job sector
<7> Total year of experience
<8> Period
<9> Project experience description
<10> Project experience value


== Information specific to CV

Based on the project experience requirement, the economic operator needs to document the candidate's project experience.
For CV used in the job application, fill in the relevant parts of project experience information.


The element `cv:EducationReference` and `cv:ProjectExperienceReference` needs to be used in the procurement process,
not in the job application process. The education reference corresponds to the educational requirement in the CV request when
the contracting authority accepts relevant experience. The project experience reference corresponds to project experience in the
CV request.

.Example of a description of project experience in CV as a response to requested education in CV request
[source, xml, indent=0]
----
include::../{snippet-dir-cv}/cv.xml[tags=ProjectExperience-req]
----
<1> Project experience identifier
<2> Type of project experience
<3> Information about contracting authority or organisation
<4> Period
<5> Project experience description: position percent, role, activities
<6> Value of project experience: total month of project participation, total project size, total project value
<7> Contact information
<8> Education reference
<9> Project experience reference


.Example of a description of project experience in a CV in the job application
[source, xml, indent=0]
----
include::../{snippet-dir-cv}/cv.xml[tags=ProjectExperience]
----
<1> Project experience identifier
<2> Type of project experience
<3> Type of industry
<4> Workplace
<5> Job sector
<6> Information about contracting authority or organisation
<7> Period
<8> Position percent
<9> Project role
<10> Description of project activities
<11> Total month of project participation
<12> Project size
<13> Project value
<14> Contact information
