= Project Experience

Project experience describes specific projects that the candidate has been a part of.
Note that this is not the same as work experience.

== Information specific to CV request

A Contracting Authority can specify a request for a project experience in several ways.
For each project experience, there must be an experience type. In some cases it may be relevant to request project experience
related to a specific industry, workplace (country) or sector.

The total years of experience can be specified in element `cv-req:RequiredTotalExperience`. It is also possible to specify a
minimum number of years (`cv-req:MinimumExperience`) and a maximum number of years (`cv-req:MaximumExperience`). The candidate must fulfill
the minimum requirement. Another option is to have either minimum or maximum years of project excperience.

In the CV request, the Contracting Authority can state the requested period for a project experience using element
`cv-req:Period`. This implies that the candidate can only refer to project experience from this period. As an example
a Contracting Authority may request information about project experience from the last five years.

The description of experience needs to be provided in element `cv-req:ExperienceDescription`, where the candidate's role must
be specified in element `cv-req:Role`. It is also possible to describe the project activities and candidate's project
position percent (e.g. must have worked 100% with the project).

The project value can be stated in element `cv-req:ExperienceValue`, where the Contracting Authority can specify the candidate's
project participation (need to be months), the size of project and the total value of the project.

.Example of the requested project experience in the CV request with alternative requirement
[source, xml, indent=0]
----
include::../{snippet-dir-cv-request}/cv-request.xml[tags=ProjectExperienceAlternative]
----
<1> Project experience identifier
<2> Project experience requirement - indicate whether a candidate needs to fulfill the project requirement.  According to codelist Requirement code (chapter 5.11).
<3> Type of project experience according to codelist Classification of Occupations (Styrk98) (chapter 5.15)
<4> Type of industry according to codelist Classification of standard industrial classification (NACE) (chapter 5.16)
<5> Workplace according to code list ISO 3166-1:Alpha2 Country codes (chapter 5.19)
<6> Job sector according to code list Sector (chapter 5.12)
<7> Total year of experience
<8> Period
<9> Candidate's position percent
<10> Role in project according to codelist Classification of Occupations (Styrk98) (chapter 5.15)
<11> Description of project activities
<12> Project participation
<13> Total Project size
<14> Project value
<15> Alternative project experience

.Example of the requested project experience in the CV request
[source, xml, indent=0]
----
include::../{snippet-dir-cv-request}/cv-request.xml[tags=ProjectExperience]
----
<1> Project experience identifier
<2> Project experience requirement - indicate whether a candidate needs to fulfill the project requirement. According to codelist Requirement code (chapter 5.11).
<3> Type of project experience according to codelist Classification of Occupations (Styrk98) (chapter 5.15)
<4> Type of industry according to codelist Classification of standard industrial classification (NACE) (chapter 5.16)
<5> Workplace according to codelist ISO 3166-1:Alpha2 Country codes (chapter 5.19)
<6> Job sector according to codelist Sector (chapter 5.12)
<7> Total year of experience
<8> Period
<9> Project experience description
<10> Project experience value. Currency according to code list ISO 4217 Currency codes (chapter 5.20)


== Information specific to CV

Based on the project experience requirement, the Economic Operator needs to document the candidate's project experience.
The element `cv:EducationReference` and `cv:ProjectExperienceReference` needs to be used in the procurement process,
not in the job application process. The education reference corresponds to the educational requirement in the CV request when
the contracting authority accepts relevant experience. The project experience reference corresponds to project experience in the
CV request.

.Example of a description of project experience in CV as a response to requested education in CV request
[source, xml, indent=0]
----
include::../{snippet-dir-cv}/cv.xml[tags=ProjectExperience-req]
----
<1> Project experience identifier
<2> Type of project experience
<3> Information about contracting authority or organisation. schemeID according to codelist Electronic address identifier (EAID) (chapter 5.18)
<4> Period
<5> Project experience description: position percent, role, activities
<6> Value of project experience: total month of project participation, total project size, total project value. Currency according to code list ISO 4217 Currency codes (chapter 5.19)
<7> Contact information
<8> Education reference
<9> Project experience reference
