= References

References that can testify the applicant's character, skills and abilities to a Contracting Authority.

== Information specific to CV request

The Contracting Authority can require a minimum total references in element `cv-req:MinimumTotalReference`.


.Example of the requested reference in the CV request
[source, xml, indent=0]
----
include::../{snippet-dir-cv-request}/cv-request.xml[tags=Reference]
----
<1> Reference identifier
<2> Total number of references required

== Information specific to CV

Based on the reference requirement, the Economic Operator needs to document the candidate's
references. 
Party information need to be stated in element `cv:Party`, with the party name and electronic
address identifier.
Relationship between the candidate and the reference-person can be stated in element `cv:Relationship`.
For example school teacher, team leader, etc.

.Example of a description of references in CV as a response to requested number of references in CV request
[source, xml, indent=0]
----
include::../{snippet-dir-cv}/cv.xml[tags=Reference]
----
<1> Reference identifier
<2> Electronic address identifier. schemeID according to codelist Electronic address identifier (EAID) (chapter 5.11)
<3> Party name
<4> Relationship to reference-person, e.g. school teacher, team leader or colleague
<5> Contact information to reference person
