= Skills

Skills contains information about candidate's abilities related to the specific work.

== Information specific to CV request

A contracting authority can state a skill requirement and an alternative requirement in the
cv request. The alternative requirement is optional, but in some cases, one can accept other skill.

To differentiate the different types of skill requirements use the element `cv-req:Requirement`.
The economic operators will only provide qualified candidates, and it makes it easier to evaluate the
candidates.

A skill can only include either element `cv-req:Type` or `cv-req:Title`. Use type if the specific
skill is defined in the skill code list, otherwise use the title. Each skill can consist of a version
number.

The contracting authority can specify details about the skill practices in element `cv-req:SkillPractice`.
The element contains information about the last practiced date, the skill practice length
(minimum requirement - must be stated as months) and if the candidate must provide a reference person.
The candidate must provide contact information to the references-person, if element
`cv-req:SkillsReference` is `True`.

.Example of the requested skill in the CV request
[source, xml, indent=0]
----
include::../{snippet-dir-cv-request}/cv-request.xml[tags=Skills]
----
<1> Skill identifier
<2> Skill requirement - indicate whether a candidate needs to fulfill the skill requirement
<3> Type of skill
<4> Skill version
<5> Last practice date
<6> Length of practice
<7> Skills reference


.Example of the requested skill in the CV request with alternative requirement
[source, xml, indent=0]
----
include::../{snippet-dir-cv-request}/cv-request.xml[tags=SkillsAlternative]
----
<1> Skill identifier
<2> Skill requirement - indicate whether a candidate needs to fulfill the skill requirement
<3> Type of skill
<4> Skill version
<5> Last practice date
<6> Length of practice
<7> Skills reference
<8> Alternative skill requirement


== Information specific to CV

Based on the skill requirement, the economic operator needs to document the candidate's
skill. For CV used in the job application process, fill in the relevant parts of
skill information.

The element `cv:SkillsReference` needs to be used in the procurement process, not in the job
application process. This is a reference to the corresponding skill requirement in the CV request.

References to where the skill has been applied can be stated in element `cv:SkillsAppliedReference/cv:ID`.
For example education, project experience, etc.

.Example of a description of skill in CV as a response to requested skill in CV request
[source, xml, indent=0]
----
include::../{snippet-dir-cv}/cv.xml[tags=Skills-req]
----
<1> Skill identifier
<2> Type of skill
<3> Skill version
<4> Last practice date
<5> Minimum length of practice
<6> Contact information
<7> Reference to where the skill is applied
<8> Skills reference

.Example of a description of skills in a CV in the job application
[source, xml, indent=0]
----
include::../{snippet-dir-cv}/cv.xml[tags=Skills]
----
<1> Skill identifier
<2> Type of skill
<3> Last practice date
<4> Minimum length of practice
<5> Contact information
<6> Reference to where the skill is applied
